import {
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiTypescript,
  SiPython,
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiGit,
  SiGithub,
  SiNodedotjs,
  SiExpress,
  SiMongodb,
  SiPostgresql,
  SiDocker,
} from 'react-icons/si';
import type { Experience, Project, Skill } from '@/types';

export const skills: Skill[] = [
  { name: 'HTML', icon: SiHtml5, color: '#E34F26' },
  { name: 'CSS', icon: SiCss3, color: '#1572B6' },
  { name: 'JavaScript', icon: SiJavascript, color: '#F7DF1E' },
  { name: 'TypeScript', icon: SiTypescript, color: '#3178C6' },
  { name: 'Python', icon: SiPython, color: '#3776AB' },
  { name: 'React', icon: SiReact, color: '#61DAFB' },
  { name: 'Next.js', icon: SiNextdotjs, color: '#FFFFFF' },
  { name: 'Tailwind CSS', icon: SiTailwindcss, color: '#06B6D4' },
  { name: 'Git', icon: SiGit, color: '#F05032' },
  { name: 'GitHub', icon: SiGithub, color: '#FFFFFF' },
  { name: 'Node.js', icon: SiNodedotjs, color: '#339933' },
  { name: 'Express', icon: SiExpress, color: '#FFFFFF' },
  { name: 'MongoDB', icon: SiMongodb, color: '#47A248' },
  { name: 'PostgreSQL', icon: SiPostgresql, color: '#4169E1' },
  { name: 'Docker', icon: SiDocker, color: '#2496ED' },
];

export const experiences: Experience[] = [
  {
    id: 1,
    title: 'Frontend Developer (Contract)',
    company: 'Karegivv',
    period: 'JAN 01 2024 - DEC 31 2024',
    logo: '/images/dev.png',
    responsibilities: [
      'Managing project timelines, coordinating tasks, and ensuring timely delivery.',
      'Designing and developing user interfaces with JavaScript frameworks and Python.',
      'Building server-side logic, managing databases, and setting up servers.',
      'Communicating with clients to understand requirements, provide updates, and address feedback.',
    ],
    technologies: ['Python', 'JavaScript', 'React', 'Next.js', 'Tailwind CSS'],
  },
  {
    id: 2,
    title: 'Frontend Developer (Contract)',
    company: 'Zaprack Technologies',
    period: 'MAR 27 2025 - PRESENT',
    logo: '/images/dev.png',
    responsibilities: [
      'Managing project timelines, coordinating tasks, and ensuring timely delivery.',
      'Designing and developing user interfaces with JavaScript frameworks and Python.',
      'Building server-side logic, managing databases, and setting up servers.',
      'Communicating with clients to understand requirements, provide updates, and address feedback.',
    ],
    technologies: ['React', 'Python', 'JavaScript', 'Next.js', 'Tailwind CSS'],
  },
  {
    id: 3,
    title: 'Frontend Developer (Contract)',
    company: 'Visiorad AI',
    period: 'MAR 27 2025 - PRESENT',
    logo: '/images/dev.png',
    responsibilities: [
      'Managing project timelines, coordinating tasks, and ensuring timely delivery.',
      'Designing and developing user interfaces with JavaScript frameworks and Python.',
      'Building server-side logic, managing databases, and setting up servers.',
      'Communicating with clients to understand requirements, provide updates, and address feedback.',
    ],
    technologies: ['React', 'Python', 'JavaScript', 'Next.js', 'Tailwind CSS'],
  },
];

export const projects: Project[] = [
  {
    id: 1,
    title: 'Karegivv health',
    description: 'A dynamic inventory Application with CRUD functionalities',
    image: '/images/projects/thankful-thoughts.png',
    technologies: ['React', 'JavaScript', 'CSS', 'Python'],
    github: 'https://github.com/HillaryNyakundi/my-inventory',
    demo: 'https://my-inventory-six.vercel.app/',
  },
  {
    id: 2,
    title: 'RwandAIR',
    description: 'A landing page website for Rwanda air travel operations built',
    image: '/images/projects/platoio.png',
    technologies: ['PostgreSQL', 'Express', 'React', 'Node.js'],
    github: 'https://github.com/HillaryNyakundi/rwandair-holidays',
    demo: 'https://rwandair-holidays.vercel.app/',
  },
  {
    id: 3,
    title: 'Barcadi',
    description: 'Cocktails store UI ',
    image: '/images/projects/drink-detector.png',
    technologies: ['CSS', 'Python', 'React', 'JavaScript', 'HTML'],
    github: 'https://github.com/HillaryNyakundi/bacardi',
    demo: 'https://barcardi.vercel.app/',
  },
  {
    id: 4,
    title: 'Guarantors Guard',
    description: 'A landing page for a SACCO business',
    image: '/images/projects/drink-detector.png',
    technologies: ['CSS', 'Python', 'React', 'JavaScript', 'HTML'],
    github: 'https://github.com/HillaryNyakundi/GuarantorsGuard',
    demo: 'https://guarantorguard.vercel.app/',
  },
];
